{% set name = "trio_asyncio" %}
{% set version = "0.9.1" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "d62684057bc74bd0e225ed1330a6a7f756351a96e031b3cb1a320a043516a6cb" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 1001
  skip: True  # [py<36]
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
    - pytest-runner
    - setuptools
  run:
    - python
    - trio >=0.5.0
    - async_generator >=1.6
    - contextvars >=2.1  # [py<37]
    - outcome


test:
  imports:
    - trio_asyncio

about:
  home: https://github.com/python-trio/trio-asyncio
  license: MIT
  license_family: MIT
  license_file: LICENSE.MIT
  summary: A re-implementation of the asyncio mainloop on top of Trio
  doc_url: http://trio-asyncio.readthedocs.io/en/latest/
  dev_url: https://github.com/python-trio/trio-asyncio

extra:
  recipe-maintainers:
    - smurfix
    - dhirschfeld
