{% set name = "trio_asyncio" %}
{% set version = "0.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 824be23b0c678c0df942816cdb57b92a8b94f264fffa89f04626b0ba2d009768

build:
  number: 0
  skip: true  # [py<36]
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
    - pytest-runner
    - setuptools
  run:
    - python
    - async_generator >=1.6  # [py<37]
    - attrs
    - contextvars >=2.1  # [py<37]
    - outcome
    - sniffio
    - trio >=0.15.0

test:
  imports:
    - trio_asyncio

about:
  home: https://github.com/python-trio/trio-asyncio
  license: MIT
  license_family: MIT
  license_file: LICENSE.MIT
  summary: A re-implementation of the asyncio mainloop on top of Trio
  doc_url: http://trio-asyncio.readthedocs.io/en/latest/
  dev_url: https://github.com/python-trio/trio-asyncio

extra:
  recipe-maintainers:
    - smurfix
    - dhirschfeld
