appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Vo4E6iENa5gwb0iMEpdGxANPB51coEjvgPgTE+aoP29HdqnofNNmkAJW2HekWe0BSJX/LtYa0QuB1VKa2EKd2jHRVQVgu3wVzq6RHJx8S/a4uW2hIy7OPPZw7k4VVA+ihu85RnSLuZxu9IYDeH68rWbHXU1Vz1B/74jgNAOTG/beMh9oi5Bh4s6uWSOQUJ0BKIHJozKAf3KA5rMiAkF0OrtNhJjsrE7SvgWPO79cz9a3C5KJXLncrFBjlLWVSwaSpxpniUnQDo1HymG7OsOeZZF0983ZwGix5nFQ3U4RbQ4LLI7i5v2vPWlFbCJvT391eCLt+gu6mSSz0W2nTSrdw3F88s+vzOQ+P3e4nucNpw3IUwoEHyG3x7zkZJgq6Z7ZKbEHTZ+Qx5woyc1aDot1iw/yxD3aV40kogEjg8SvqmXRthT/t0y0VQyBPcf9JsvImU/46BoABmtrhgYA20f1lKH3F7TbcRCjz/IrbDKwACc/+G7VtUNPznfeeborDvow5drqQYuSfMgbsk5jP/LsZ5vf0YpmIAg9JXcypQ+Z8kqhfDteFUAhFt29Cbx3cDhHeTWdk3vY5w1fKzZPLKTg4KTeZxIYgVwE80sNNTdyDiQ1voJJO8F/cv8SwoqHi3I6z9kA0D8Yr1BZUurJACJnRtpNj1EtKMBeUmydCUtEEuI=}
