travis:
  secure:
    BINSTAR_TOKEN: oazT5OitGbL+Rj6yHngmGsBld8VCPg8NSVkPhJs5rYpDFupQptFWk+WJzXBtha+Q7dPAPn1TlvRsZln5m3JD3u58uqSi9G9WIJZjORXsNUFdqiL78vEOaODcsXBs4kX0XNJ3a8aYgYIQSZpWV1154KIYiuJhXZDAg3tDuFL9sY1utWbOBsoRp+cexyedwcii+MFQXf607pDQFC+tRjTcJi5psoQylfqY63KlYF6rD/Q5JuPvBU+wdeC0hALofRy+7t8Phn1LR2BMbOn710EQeIESCD1D/IhidAMJNDX6XEoIZ7L6c9eNCdgSrbDjf7WPnzyeqWHb7WHDzcx/vF2TbWcx7NksG2TVZeiAqQvueO0Nhm/Yt6AGkKg0Wi2XX4dJBtlRnjl7sQkT6y5jnA/QPtYPtRMlQoXgjQuxIA0+laEVFKmRVMibssQJ0Ui7h74jUmcfgqibF4e/CK8z587kZuDJo2iP30+8uxmd4aFRSLQu5WPn/OOQOa7zoWmvEB2OiXqTI8B8OIIpEJ6cYs0hUkoNwaiL4zVV3XnQwZEs+eLchc314vbLYemzbALyYiEPoMf2wERLIM/l4Dss6sWJukq6UiC+qzxDqbC1GS93LAzM2NFMDxWloRgWHWWdh+hPjslKf2QIkHJm3BS3jZ8pOKus3wxGYnpsJMcYjZTbTH8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
